import type { MessageCatalog } from './types.js'

export const de = {
  'app.title': 'Rudralipi',
  'panel.blocks': 'Bausteine',
  'panel.structure': 'Dokumentstruktur',
  'panel.properties': 'Eigenschaften',
  'panel.diagnostics': 'Diagnosen',
  'panel.preview': 'Vorschau',
  'toolbar.undo': 'Rückgängig',
  'toolbar.redo': 'Wiederholen',
  'toolbar.save': 'Speichern',
  'toolbar.export': 'Exportieren',
  'toolbar.preview': 'Vorschau',
  'toolbar.json': 'Dokument-JSON',
  'toolbar.zoomIn': 'Vergrößern',
  'toolbar.zoomOut': 'Verkleinern',
  'toolbar.bold': 'Fett',
  'toolbar.italic': 'Kursiv',
  'toolbar.underline': 'Unterstrichen',
  'toolbar.strike': 'Durchgestrichen',
  'toolbar.code': 'Inline-Code',
  'toolbar.superscript': 'Hochgestellt',
  'toolbar.subscript': 'Tiefgestellt',
  'toolbar.bulletList': 'Aufzählung',
  'toolbar.orderedList': 'Nummerierte Liste',
  'action.add': 'Hinzufügen',
  'action.delete': 'Löschen',
  'action.duplicate': 'Duplizieren',
  'action.moveUp': 'Nach oben',
  'action.moveDown': 'Nach unten',
  'action.close': 'Schließen',
  'action.search': 'Suchen',
  'action.reset': 'Zurücksetzen',
  'action.addRow': 'Zeile hinzufügen',
  'action.addColumn': 'Spalte hinzufügen',
  'action.addSignatureLine': 'Unterschriftszeile hinzufügen',
  'action.removeRow': 'Zeile entfernen',
  'action.removeColumn': 'Spalte entfernen',
  'action.removeSignatureLine': 'Unterschriftszeile entfernen',
  'block.heading': 'Überschrift',
  'block.richText': 'Rich-Text',
  'block.image': 'Bild',
  'block.mergeField': 'Serienfeld',
  'block.table': 'Tabelle',
  'block.columns': 'Spalten',
  'block.divider': 'Trennlinie',
  'block.spacer': 'Abstand',
  'block.header': 'Kopfzeile',
  'block.footer': 'Fußzeile',
  'block.signature': 'Unterschrift',
  'block.conditional': 'Bedingter Abschnitt',
  'block.pageBreak': 'Seitenumbruch',
  'block.unknown': 'Unbekannte Erweiterung',
  'field.level': 'Ebene',
  'field.text': 'Text',
  'field.alt': 'Alternativtext',
  'field.asset': 'Asset',
  'field.width': 'Breite',
  'field.alignment': 'Ausrichtung',
  'field.fit': 'Anpassung',
  'field.mergeField': 'Feld',
  'field.fallback': 'Ersatzwert',
  'field.format': 'Format',
  'field.columns': 'Spalten',
  'field.rows': 'Zeilen',
  'field.repeatHeader': 'Tabellenkopf wiederholen',
  'field.allowRowSplit': 'Zeilen über Seiten umbrechen',
  'field.gap': 'Abstand',
  'field.variant': 'Variante',
  'field.weight': 'Stärke',
  'field.size': 'Größe',
  'field.repeat': 'Wiederholung',
  'field.showPageNumber': 'Seitenzahl anzeigen',
  'field.layout': 'Layout',
  'field.condition': 'Bedingung',
  'field.conditionField': 'Bedingungsfeld',
  'field.conditionOperator': 'Bedingungsoperator',
  'field.conditionValue': 'Bedingungswert',
  'field.columnHeader': 'Spaltenüberschrift',
  'field.columnWidth': 'Spaltenbreite',
  'field.signatureLabel': 'Unterschriftsbeschriftung',
  'field.signerField': 'Unterzeichnerfeld',
  'field.imageAsset': 'Unterschriftsbild',
  'field.trueContent': 'Wenn wahr',
  'field.falseContent': 'Andernfalls',
  'field.pageSize': 'Seitengröße',
  'field.orientation': 'Ausrichtung',
  'field.margins': 'Seitenränder',
  'field.locale': 'Sprache',
  'status.blockMoved': '{block} wurde an Position {position} verschoben.',
  'status.saved': 'Dokument gespeichert.',
  'status.loaded': 'Dokument geladen.',
  'status.invalidDocument': 'Das Dokument ist ungültig.',
  'status.noSelection':
    'Wählen Sie einen Baustein aus, um seine Eigenschaften zu bearbeiten.',
  'status.noDiagnostics': 'Keine Diagnosen.',
  'status.loadingPreview': 'Vorschau wird vorbereitet…',
  'commandPalette.title': 'Befehlspalette',
  'commandPalette.placeholder': 'Befehl eingeben…',
  'a11y.dragInstructions':
    'Leertaste zum Aufnehmen, Pfeiltasten zum Verschieben und Leertaste zum Ablegen drücken.',
  'a11y.blockSelected': '{block} ausgewählt.',
  'a11y.editorLabel': 'Rudralipi-Dokumenteditor',
  'locale.en': 'Englisch',
  'locale.de': 'Deutsch',
  'locale.it': 'Italienisch',
  'locale.tr': 'Türkisch',
  'preview.title': 'Dokumentvorschau',
  'preview.browser': 'Browser',
  'preview.print': 'Druck',
  'diagnostic.error': 'Fehler',
  'diagnostic.warning': 'Warnung',
  'diagnostic.info': 'Information',
} satisfies MessageCatalog
