export const en = {
  'app.title': 'Rudralipi',
  'panel.blocks': 'Blocks',
  'panel.structure': 'Document structure',
  'panel.properties': 'Properties',
  'panel.diagnostics': 'Diagnostics',
  'panel.preview': 'Preview',
  'toolbar.undo': 'Undo',
  'toolbar.redo': 'Redo',
  'toolbar.save': 'Save',
  'toolbar.export': 'Export',
  'toolbar.preview': 'Preview',
  'toolbar.json': 'Document JSON',
  'toolbar.zoomIn': 'Zoom in',
  'toolbar.zoomOut': 'Zoom out',
  'toolbar.bold': 'Bold',
  'toolbar.italic': 'Italic',
  'toolbar.underline': 'Underline',
  'toolbar.strike': 'Strikethrough',
  'toolbar.code': 'Inline code',
  'toolbar.superscript': 'Superscript',
  'toolbar.subscript': 'Subscript',
  'toolbar.bulletList': 'Bullet list',
  'toolbar.orderedList': 'Ordered list',
  'action.add': 'Add',
  'action.delete': 'Delete',
  'action.duplicate': 'Duplicate',
  'action.moveUp': 'Move up',
  'action.moveDown': 'Move down',
  'action.close': 'Close',
  'action.search': 'Search',
  'action.reset': 'Reset',
  'action.addRow': 'Add row',
  'action.addColumn': 'Add column',
  'action.addSignatureLine': 'Add signature line',
  'action.removeRow': 'Remove row',
  'action.removeColumn': 'Remove column',
  'action.removeSignatureLine': 'Remove signature line',
  'block.heading': 'Heading',
  'block.richText': 'Rich text',
  'block.image': 'Image',
  'block.mergeField': 'Merge field',
  'block.table': 'Table',
  'block.columns': 'Columns',
  'block.divider': 'Divider',
  'block.spacer': 'Spacer',
  'block.header': 'Header',
  'block.footer': 'Footer',
  'block.signature': 'Signature',
  'block.conditional': 'Conditional section',
  'block.pageBreak': 'Page break',
  'block.unknown': 'Unknown extension',
  'field.level': 'Level',
  'field.text': 'Text',
  'field.alt': 'Alternative text',
  'field.asset': 'Asset',
  'field.width': 'Width',
  'field.alignment': 'Alignment',
  'field.fit': 'Fit',
  'field.mergeField': 'Field',
  'field.fallback': 'Fallback',
  'field.format': 'Format',
  'field.columns': 'Columns',
  'field.rows': 'Rows',
  'field.repeatHeader': 'Repeat table header',
  'field.allowRowSplit': 'Allow rows to split across pages',
  'field.gap': 'Gap',
  'field.variant': 'Variant',
  'field.weight': 'Weight',
  'field.size': 'Size',
  'field.repeat': 'Repeat',
  'field.showPageNumber': 'Show page number',
  'field.layout': 'Layout',
  'field.condition': 'Condition',
  'field.conditionField': 'Condition field',
  'field.conditionOperator': 'Condition operator',
  'field.conditionValue': 'Condition value',
  'field.columnHeader': 'Column heading',
  'field.columnWidth': 'Column width',
  'field.signatureLabel': 'Signature label',
  'field.signerField': 'Signer field',
  'field.imageAsset': 'Signature image',
  'field.trueContent': 'When true',
  'field.falseContent': 'Otherwise',
  'field.pageSize': 'Page size',
  'field.orientation': 'Orientation',
  'field.margins': 'Margins',
  'field.locale': 'Language',
  'status.blockMoved': '{block} moved to position {position}.',
  'status.saved': 'Document saved.',
  'status.loaded': 'Document loaded.',
  'status.invalidDocument': 'The document is invalid.',
  'status.noSelection': 'Select a block to edit its properties.',
  'status.noDiagnostics': 'No diagnostics.',
  'status.loadingPreview': 'Preparing preview…',
  'commandPalette.title': 'Command palette',
  'commandPalette.placeholder': 'Type a command…',
  'a11y.dragInstructions':
    'Press Space to pick up a block, arrow keys to move it, and Space to drop.',
  'a11y.blockSelected': '{block} selected.',
  'a11y.editorLabel': 'Rudralipi document editor',
  'locale.en': 'English',
  'locale.de': 'German',
  'locale.it': 'Italian',
  'locale.tr': 'Turkish',
  'preview.title': 'Document preview',
  'preview.browser': 'Browser',
  'preview.print': 'Print',
  'diagnostic.error': 'Error',
  'diagnostic.warning': 'Warning',
  'diagnostic.info': 'Information',
} as const
