import type { MessageCatalog } from './types.js'

export const it = {
  'app.title': 'Rudralipi',
  'panel.blocks': 'Blocchi',
  'panel.structure': 'Struttura del documento',
  'panel.properties': 'Proprietà',
  'panel.diagnostics': 'Diagnostica',
  'panel.preview': 'Anteprima',
  'toolbar.undo': 'Annulla',
  'toolbar.redo': 'Ripeti',
  'toolbar.save': 'Salva',
  'toolbar.export': 'Esporta',
  'toolbar.preview': 'Anteprima',
  'toolbar.json': 'JSON del documento',
  'toolbar.zoomIn': 'Ingrandisci',
  'toolbar.zoomOut': 'Riduci',
  'toolbar.bold': 'Grassetto',
  'toolbar.italic': 'Corsivo',
  'toolbar.underline': 'Sottolineato',
  'toolbar.strike': 'Barrato',
  'toolbar.code': 'Codice inline',
  'toolbar.superscript': 'Apice',
  'toolbar.subscript': 'Pedice',
  'toolbar.bulletList': 'Elenco puntato',
  'toolbar.orderedList': 'Elenco numerato',
  'action.add': 'Aggiungi',
  'action.delete': 'Elimina',
  'action.duplicate': 'Duplica',
  'action.moveUp': 'Sposta su',
  'action.moveDown': 'Sposta giù',
  'action.close': 'Chiudi',
  'action.search': 'Cerca',
  'action.reset': 'Reimposta',
  'action.addRow': 'Aggiungi riga',
  'action.addColumn': 'Aggiungi colonna',
  'action.addSignatureLine': 'Aggiungi riga firma',
  'action.removeRow': 'Rimuovi riga',
  'action.removeColumn': 'Rimuovi colonna',
  'action.removeSignatureLine': 'Rimuovi riga firma',
  'block.heading': 'Titolo',
  'block.richText': 'Testo formattato',
  'block.image': 'Immagine',
  'block.mergeField': 'Campo dati',
  'block.table': 'Tabella',
  'block.columns': 'Colonne',
  'block.divider': 'Divisore',
  'block.spacer': 'Spaziatore',
  'block.header': 'Intestazione',
  'block.footer': 'Piè di pagina',
  'block.signature': 'Firma',
  'block.conditional': 'Sezione condizionale',
  'block.pageBreak': 'Interruzione di pagina',
  'block.unknown': 'Estensione sconosciuta',
  'field.level': 'Livello',
  'field.text': 'Testo',
  'field.alt': 'Testo alternativo',
  'field.asset': 'Risorsa',
  'field.width': 'Larghezza',
  'field.alignment': 'Allineamento',
  'field.fit': 'Adattamento',
  'field.mergeField': 'Campo',
  'field.fallback': 'Valore alternativo',
  'field.format': 'Formato',
  'field.columns': 'Colonne',
  'field.rows': 'Righe',
  'field.repeatHeader': "Ripeti l'intestazione della tabella",
  'field.allowRowSplit': 'Consenti la divisione delle righe tra pagine',
  'field.gap': 'Spazio',
  'field.variant': 'Variante',
  'field.weight': 'Spessore',
  'field.size': 'Dimensione',
  'field.repeat': 'Ripetizione',
  'field.showPageNumber': 'Mostra numero di pagina',
  'field.layout': 'Layout',
  'field.condition': 'Condizione',
  'field.conditionField': 'Campo condizione',
  'field.conditionOperator': 'Operatore condizione',
  'field.conditionValue': 'Valore condizione',
  'field.columnHeader': 'Intestazione colonna',
  'field.columnWidth': 'Larghezza colonna',
  'field.signatureLabel': 'Etichetta firma',
  'field.signerField': 'Campo firmatario',
  'field.imageAsset': 'Immagine firma',
  'field.trueContent': 'Se vero',
  'field.falseContent': 'Altrimenti',
  'field.pageSize': 'Formato pagina',
  'field.orientation': 'Orientamento',
  'field.margins': 'Margini',
  'field.locale': 'Lingua',
  'status.blockMoved': '{block} spostato alla posizione {position}.',
  'status.saved': 'Documento salvato.',
  'status.loaded': 'Documento caricato.',
  'status.invalidDocument': 'Il documento non è valido.',
  'status.noSelection': 'Seleziona un blocco per modificarne le proprietà.',
  'status.noDiagnostics': 'Nessuna diagnostica.',
  'status.loadingPreview': 'Preparazione anteprima…',
  'commandPalette.title': 'Tavolozza comandi',
  'commandPalette.placeholder': 'Digita un comando…',
  'a11y.dragInstructions':
    'Premi Spazio per prendere un blocco, usa le frecce per spostarlo e Spazio per rilasciarlo.',
  'a11y.blockSelected': '{block} selezionato.',
  'a11y.editorLabel': 'Editor documenti Rudralipi',
  'locale.en': 'Inglese',
  'locale.de': 'Tedesco',
  'locale.it': 'Italiano',
  'locale.tr': 'Turco',
  'preview.title': 'Anteprima documento',
  'preview.browser': 'Browser',
  'preview.print': 'Stampa',
  'diagnostic.error': 'Errore',
  'diagnostic.warning': 'Avviso',
  'diagnostic.info': 'Informazione',
} satisfies MessageCatalog
