import type { MessageCatalog } from './types.js'

export const tr = {
  'app.title': 'Rudralipi',
  'panel.blocks': 'Bloklar',
  'panel.structure': 'Belge yapısı',
  'panel.properties': 'Özellikler',
  'panel.diagnostics': 'Tanılar',
  'panel.preview': 'Önizleme',
  'toolbar.undo': 'Geri al',
  'toolbar.redo': 'Yinele',
  'toolbar.save': 'Kaydet',
  'toolbar.export': 'Dışa aktar',
  'toolbar.preview': 'Önizleme',
  'toolbar.json': 'Belge JSON',
  'toolbar.zoomIn': 'Yakınlaştır',
  'toolbar.zoomOut': 'Uzaklaştır',
  'toolbar.bold': 'Kalın',
  'toolbar.italic': 'İtalik',
  'toolbar.underline': 'Altı çizili',
  'toolbar.strike': 'Üstü çizili',
  'toolbar.code': 'Satır içi kod',
  'toolbar.superscript': 'Üst simge',
  'toolbar.subscript': 'Alt simge',
  'toolbar.bulletList': 'Madde işaretli liste',
  'toolbar.orderedList': 'Numaralı liste',
  'action.add': 'Ekle',
  'action.delete': 'Sil',
  'action.duplicate': 'Çoğalt',
  'action.moveUp': 'Yukarı taşı',
  'action.moveDown': 'Aşağı taşı',
  'action.close': 'Kapat',
  'action.search': 'Ara',
  'action.reset': 'Sıfırla',
  'action.addRow': 'Satır ekle',
  'action.addColumn': 'Sütun ekle',
  'action.addSignatureLine': 'İmza satırı ekle',
  'action.removeRow': 'Satırı kaldır',
  'action.removeColumn': 'Sütunu kaldır',
  'action.removeSignatureLine': 'İmza satırını kaldır',
  'block.heading': 'Başlık',
  'block.richText': 'Zengin metin',
  'block.image': 'Görsel',
  'block.mergeField': 'Birleştirme alanı',
  'block.table': 'Tablo',
  'block.columns': 'Sütunlar',
  'block.divider': 'Ayırıcı',
  'block.spacer': 'Boşluk',
  'block.header': 'Üst bilgi',
  'block.footer': 'Alt bilgi',
  'block.signature': 'İmza',
  'block.conditional': 'Koşullu bölüm',
  'block.pageBreak': 'Sayfa sonu',
  'block.unknown': 'Bilinmeyen uzantı',
  'field.level': 'Düzey',
  'field.text': 'Metin',
  'field.alt': 'Alternatif metin',
  'field.asset': 'Varlık',
  'field.width': 'Genişlik',
  'field.alignment': 'Hizalama',
  'field.fit': 'Sığdırma',
  'field.mergeField': 'Alan',
  'field.fallback': 'Yedek değer',
  'field.format': 'Biçim',
  'field.columns': 'Sütunlar',
  'field.rows': 'Satırlar',
  'field.repeatHeader': 'Tablo başlığını yinele',
  'field.allowRowSplit': 'Satırların sayfalar arasında bölünmesine izin ver',
  'field.gap': 'Aralık',
  'field.variant': 'Çeşit',
  'field.weight': 'Kalınlık',
  'field.size': 'Boyut',
  'field.repeat': 'Yineleme',
  'field.showPageNumber': 'Sayfa numarasını göster',
  'field.layout': 'Düzen',
  'field.condition': 'Koşul',
  'field.conditionField': 'Koşul alanı',
  'field.conditionOperator': 'Koşul işleci',
  'field.conditionValue': 'Koşul değeri',
  'field.columnHeader': 'Sütun başlığı',
  'field.columnWidth': 'Sütun genişliği',
  'field.signatureLabel': 'İmza etiketi',
  'field.signerField': 'İmzalayan alanı',
  'field.imageAsset': 'İmza görseli',
  'field.trueContent': 'Doğru olduğunda',
  'field.falseContent': 'Aksi durumda',
  'field.pageSize': 'Sayfa boyutu',
  'field.orientation': 'Yön',
  'field.margins': 'Kenar boşlukları',
  'field.locale': 'Dil',
  'status.blockMoved': '{block}, {position}. konuma taşındı.',
  'status.saved': 'Belge kaydedildi.',
  'status.loaded': 'Belge yüklendi.',
  'status.invalidDocument': 'Belge geçersiz.',
  'status.noSelection': 'Özelliklerini düzenlemek için bir blok seçin.',
  'status.noDiagnostics': 'Tanı yok.',
  'status.loadingPreview': 'Önizleme hazırlanıyor…',
  'commandPalette.title': 'Komut paleti',
  'commandPalette.placeholder': 'Bir komut yazın…',
  'a11y.dragInstructions':
    'Bloğu almak için Boşluk tuşuna, taşımak için ok tuşlarına ve bırakmak için tekrar Boşluk tuşuna basın.',
  'a11y.blockSelected': '{block} seçildi.',
  'a11y.editorLabel': 'Rudralipi belge düzenleyicisi',
  'locale.en': 'İngilizce',
  'locale.de': 'Almanca',
  'locale.it': 'İtalyanca',
  'locale.tr': 'Türkçe',
  'preview.title': 'Belge önizlemesi',
  'preview.browser': 'Tarayıcı',
  'preview.print': 'Yazdır',
  'diagnostic.error': 'Hata',
  'diagnostic.warning': 'Uyarı',
  'diagnostic.info': 'Bilgi',
} satisfies MessageCatalog
